### ISSUE TITLE
enable auto deployment on tags to Github Releases

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/compreffor#19]
Someone with push access could generate Github authentication tokens and un-comment the `deploy` section in `.travis.yml` and `.appveyor.yml`.
Then, the next time a tag is pushed, wheels will be automatically uploaded to Github Releases page.

**Comment by behdad** [comment]
Thanks Cosimo.  I gave you commit access.

**Comment by anthrotype** [comment]
Thanks Behdad. I've added the secure Github token to `.travis.yml` in 7447370f149adc9f462d00622c7b68621d866d51
So now the next time a tag is pushed, wheels for OSX and Linux (and sdist) will be uploaded to Github Releases. For Appveyor we first need to enable it (#21), then we can do the same and upload Windows wheels to Github as well.

I would also like to set up PyPI deployment for compreffor. I can take care of the CI setup and also of maintaining the compreffor PyPI account, if you don't mind.

**Comment by anthrotype** [comment]
Done!
https://github.com/googlei18n/compreffor/releases
