### ISSUE TITLE
Enable Appveyor CI for push and pull requests

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/compreffor#21]
I tried to open one from my personal appveyor account but it doesn't trigger
https://ci.appveyor.com/project/anthrotype/compreffor-16l0f 

I believe it needs to be an “organizational” account registered under `googlei18n`
https://www.appveyor.com/docs/team-setup/

**Comment by jamesgk** [comment]
This also requires an organizational email address to associate with the AppVeyor account?

**Comment by anthrotype** [comment]
maybe.. I've never done it myself.

**Comment by jamesgk** [comment]
I found the AppVeyor docs a bit dense. But this is what I was basing that question off of: https://www.appveyor.com/docs/team-setup/#register-a-new-appveyor-account-with-emailpassword

**Comment by anthrotype** [comment]
I guess it just means it needs to be an address which is not already registered with Appveyor. Being it an organization account it would make sense for it to not being tied to any one individual...

**Comment by anthrotype** [comment]
@jamesgk is it enabled now?

**Comment by jamesgk** [comment]
No, we don't have an organizational email address to use. I guess a quick fix would be to try to register google-font-team@gmail.com or something like that. (Though the github group is for all of Google i18n....) Or maybe we can use an internal google.com list. @behdad, any opinion?

**Comment by anthrotype** [comment]
It's live now!
https://ci.appveyor.com/project/fonttools/compreffor
