### ISSUE TITLE
`callsubr` operator in global subroutines

### ISSUE THREAD

**Issue by mashabow** [googlei18n/compreffor#39]
Currently, compreffor may generate some global subroutines which contain `callsubr` operator.  But according to https://github.com/fonttools/fonttools/issues/856#issuecomment-283779329, it is invalid:

> I asked my colleagues and confirmed that it's invalid to use the `callsubr` operator in global subroutines.

In fact, I found the above fonttools' bug when trying to subset a font subroutinized by compreffor.

**Comment by anthrotype** [comment]
thanks @mashabow 
honestly, I am not sure how to fix this, or even whether it actually is something that needs to be fixed.

Maybe the following comment provides some clue as to how compreffor deals with such local subroutines called from global ones:

>  # assert this is a local or global only used by one FD
 
https://github.com/googlei18n/compreffor/blob/932a60b/src/python/compreffor/pyCompressor.py#L901

I'm hoping @behdad could have a look at this when he has some spare time.
@mashabow, you are welcome to send a pull request, of course.

**Comment by mashabow** [comment]
> honestly, I am not sure how to fix this, or even whether it actually is something that needs to be fixed.

I am not sure whether it should be fixed, too. As @miguelsousa [says](https://github.com/fonttools/fonttools/issues/856#issuecomment-283868476), it doesn't seem this restriction has been documented. In addition, such fonts work fine in major applications as far as I checked.

**Comment by behdad** [comment]
Should be possible to not generate those. Though, someone who understand the code well needs to go in and do that surgery.

**Comment by mashabow** [comment]
https://github.com/googlei18n/compreffor/blob/932a60b/src/python/compreffor/pyCompressor.py#L753-L787

This block seems to put each candidate subroutine in global or local subroutines. So if we really want to avoid such "invalid" global ones, we have to check whether a candidate `subr` contains `callsubr` operator before calling `Compreffor.insert_by_usage(subr, gsubrs)`.

**Comment by behdad** [comment]
> https://github.com/googlei18n/compreffor/blob/932a60b/src/python/compreffor/pyCompressor.py#L753-L787

Somewhere around that, yes.

**Comment by behdad** [comment]
> This block seems to put each candidate subroutine in global or local subroutines

If that block is to be trusted, looks like it only does that if there's only one FontDict.  Is that consistent with what you are seeing?  If yes, we can update subsetter to also do that.  Makes sense to me.

**Comment by mashabow** [comment]
>> This block seems to put each candidate subroutine in global or local subroutines
>
> If that block is to be trusted, looks like it only does that if there's only one FontDict.

No. It may insert into global subroutines, even if there are multiple FontDicts. This is a pseudocode for that block:

```py
while candidate_subrs and (some lsubrs/gsubrs has space):
    subr = candidtate_subrs.pop()
    if subr is called from glyphs which are all in one FD:
        if gsubrs has space:
            if lsubrs has space:
                insert subr into gsubrs or lsubrs, minimizing the cost
            else:
                insert subr into gsubrs
        else lsubrs has space:
            insert subr into lsubrs
        else:
            no room, give up inserting
    else:
        if gsubrs has space:
            insert subr into gsubrs
        else:
            no room, give up inserting
```
