### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/compreffor#6]
ufo2ft depends on compreffor now, but there is no setup.py file or any install instructions that I can find.

**Comment by behdad** [comment]
@adrientetar just added some.  It doesn't compile the C++ version (which is faster), but should at least unblock people.

Though, compreffor should definitely be optional for ufo2ft.

**Comment by khaledhosny** [comment]
I this this can be closed now, thanks to @adrientetar and @anthrotype.
